### ISSUE TITLE
gearsyncd log level is set to NOTICE irrespective of user set log level post config reload/docker restart

### ISSUE THREAD

**Issue by jaganbal-a** [sonic-net/sonic-sairedis#1300]
LOG NOTICE is explicitly set in discover().
https://github.com/sonic-net/sonic-sairedis/blame/master/syncd/SaiDiscovery.cpp#L271

With the command "swssloglevel -l DEBUG -c gearsyncd", the log level of the gearsyncd is set to DEBUG, but post config reload/process restart this will get over written with NOTICE in the discover API which needs to be fixed.

Any user set log level should be restored post config reload/docker/process restart.

**Comment by kcudnik** [comment]
Yes ,thanks for notice that, I will fix this

**Comment by kcudnik** [comment]
the problem here is that, SAI don't have api that can get current api log level, only set loglevel function is present, but we can store current level, and pass is to  sai discovery, but this is kind a woakaround

**Comment by kcudnik** [comment]
ok, so the problem here is that we would need to collect user level to api/loglevel map, and pass it from Syncd class to Switch class and then to SaiDiscovery class, but Switch is also used in SingleReiniter and HardReiniter, curing cold boot, and it would cause to pass this new object through lot of classes, but i have other idea, to artificially implement get log level in vendorSai
